// EDIT CONTROLLER


// NG-CLICK BUTTON (TO VISIT AND VISITED VIEWS) WILL BRING UP EDIT VIEW

// CONTECT FOR EDITING IS DIFFERENT THAN SUBMIT OR ADD. MORE SIMILAR TO ADD

// SUBMIT BUTTON TO UPDATE OBJECT AND RETURN TO SCREEN THEY WERE AT

// CONFIRMATION THAT INFORMATION WAS UPDATED

// ADD DELETE BUTTON TO DELETE THIS ITEM(?)
