// EXPANDED VIEW


// NG-CLICK BRINGS USER TO VIEW WITH MORE INFORMATION (POPUP?)

// BUTTON TO RETURN TO PREVIOUS VIEW

// CLICKING ON ADDRESS BRINGS USER TO HTML LINK (MAPS) TO DIRECT THEM TO THE RIGHT LOCATION

// BRING IN IMAGE FROM ONLINE(?)
