// SUBMIT PLACE AS VISITED: TRUE


// NG-CLICK: OPEN PLACE FOR EDITING VIEW (SEND TO EDIT WITH CORRECT CONTENT)

// CORRECT CONTENT TO EDIT

// CLICKING SUBMIT BUTTON AGAIN SENDS COMPLETED EDITED FORM/OBJECT TO VISITED VIEW

// CONFIRMATION THAT PLACE WAS SUBMITTED AS VISITED
