// VISITED CONTROLLER VIEW
myApp.controller('VisitedController', ['UserService', function(UserService){
  console.log('VisitedController sourced!');
  var visited = this;
}]);

// SORT PLACES BY DATE VISITED

// BRING IN IMAGE(THUMBNAIL) FROM ONLINE(?)

// FILTER PLACES BY LOCATION AND TYPE

// GET MORE INFORMATION ABOUT PLACE

// SEARCH FOR PLACE BY NAME

// EDIT EXISTING PLACE

// DELETE EXISTING PLACE
// ADD DELETE BUTTON TO DELETE THIS ITEM(?)
